version: "3.9"

services:
  app:
    # Image will be updated by CI to include the specific tag (git SHA)
    image: your-dockerhub-username/noteforge:latest
    container_name: noteforge-prod
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
