version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: noteforge-dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/cms
      NEXT_WEBPACK_USEPOLLING: 1
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: noteforge-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cms"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     container_name: noteforge-dev
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#       - /app/node_modules
