name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/noteforge:${{ github.sha }}
          build-args: NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}

      - name: Deploy to AWS VM via SSH
        shell: bash
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Disk usage before cleanup:" && df -h || true
            echo "Docker disk usage before cleanup:" && docker system df || true

            # Stop and remove old container if exists
            docker ps -q --filter "name=noteforge" | grep -q . && docker stop noteforge && docker rm noteforge || true

            echo "Pulling image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/noteforge:${{ github.sha }}

            echo "Starting container..."
            docker run -d \
              --name noteforge \
              --restart unless-stopped \
              -p 80:3000 \
              --env-file ${{ secrets.EC2_ENV_FILE_PATH }} \
              -e PORT=3000 \
              -e HOSTNAME=0.0.0.0 \
              ${{ secrets.DOCKERHUB_USERNAME }}/noteforge:${{ github.sha }}
          EOF
